#!/bin/bash

echo "Using makefile(s): $(make -p --recon | grep MAKEFILE_LIST | cut -d" " -f4-)"
make -p --recon >/dev/null
echo [ $? == 2 ]

# Colors
source $(dirname $BASH_SOURCE)/colors.sh

COMMAND_COLOR="$COLOR_PREFIX$LIGHTPURPLE$COLOR_POSTFIX"
ERROR_COLOR="$COLOR_PREFIX$LIGHTRED$COLOR_POSTFIX"
NO_COLOR="${COLOR_PREFIX}0${COLOR_POSTFIX}"

COMMAND="make"

# TODO loop on file modification
for RULE in "$@"
do
  OUTPUT=$($COMMAND $RULE 2>&1 >/dev/null)
  #TODO respect newlines in OUTPUT
  if [ $? != 0 ]; then
    echo -e ${ERROR_COLOR}${COMMAND} ${RULE}${NO_COLOR}:
  else
    echo -e ${COMMAND_COLOR}${COMMAND} ${RULE}${NO_COLOR}: done
  fi
  echo ${OUTPUT}
done
