#!/bin/bash

# TODO print out working configuration file

# Colors

Black        0;30
Red          0;31
Green        0;32
Brown/Orange 0;33
Blue         0;34
Purple       0;35
Cyan         0;36
Light Gray   0;37

DarkGray     1;30
LightRed     1;31
LightGreen   1;32
Yellow       1;33
LightBlue    1;34
LightPurple  1;35
LightCyan    1;36
White        1;37

COMMAND="make"

# TODO loop on file modification
for RULE in "$@"
do
  # TODO color code labels
  echo $COMMAND $RULE:
  $COMMAND $RULE
done
